# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8944b2e3a94032aef2569288484fe92e2c0234efff4a9d5130265fc78f481c30ff83554adb4a776b2bc366aab9cef8cf0cbd674d9513a3c7c406da0a206be68

test:
  secret_key_base: e5ed2649afffb6982ee7061870774226996370e966f432d5b4ded82f1e23b4d86de6e421854a27a9a8528ab4ebe34117d4894ae59ef9e924f838b07e023312f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
